export const dummyCharacters = [
  {
    id: "0",
    name: "Alice Stine",
    age: "26",
    location: "Colchester",
    profession: "Unemployed",
    species: "Human",
    imageURL: "https://d2folr83karyot.cloudfront.net/character/21709/1.jpg",
    description:
      "Alice is a young woman in her mid-twenties, with a mysterious aura that makes her stand out in a crowd. She has long, curly brown hair and piercing green eyes that seem to see right through you. Alice is a free spirit, always seeking adventure and new experiences. Despite her carefree nature, she possesses a sharp intellect and a cunning wit that makes her a formidable opponent in any situation. However, her past is shrouded in secrets, and she guards her heart closely, making it difficult for others to get close to her. Despite this, Alice remains optimistic and full of life, always eager to see what the world has in store for her next.",
    stats: {
      physical: [
        { name: "Str", stat: 3 },
        { name: "Dex", stat: 2 },
        { name: "Sta", stat: 3 },
      ],
      mental: [
        { name: "Int", stat: 3 },
        { name: "Wis", stat: 2 },
        { name: "Wit", stat: 3 },
      ],
      social: [
        { name: "Pre", stat: 3 },
        { name: "Man", stat: 2 },
        { name: "Com", stat: 3 },
      ],
      skillPhy: [
        { name: "Athletics", stat: 3 },
        { name: "Brawl", stat: 2 },
        { name: "Drive", stat: 3 },
        { name: "Firearms", stat: 3 },
        { name: "Larceny", stat: 2 },
        { name: "Stealth", stat: 3 },
        { name: "Survival", stat: 3 },
        { name: "Weaponry", stat: 2 },
      ],
      skillMen: [
        { name: "Academics", stat: 3 },
        { name: "Computer", stat: 2 },
        { name: "Crafts", stat: 3 },
        { name: "Investigation", stat: 3 },
        { name: "Medicine", stat: 2 },
        { name: "Occult", stat: 3 },
        { name: "Politics", stat: 3 },
        { name: "Science", stat: 2 },
      ],
      skillSoc: [
        { name: "Animal Ken", stat: 3 },
        { name: "Empathy", stat: 2 },
        { name: "Expression", stat: 3 },
        { name: "Intimidation", stat: 3 },
        { name: "Persuasion", stat: 2 },
        { name: "Socialize", stat: 3 },
        { name: "Streetwise", stat: 3 },
        { name: "Subterfuge", stat: 2 },
      ],
    },
  },
  {
    id: "1",
    name: "Charlie Decker",
    age: "32",
    location: "Colchester",
    profession: "Private Investigator",
    species: "Human",
    imageURL: "https://d2folr83karyot.cloudfront.net/character/22298/1.jpg",
    description:
      "Charlie Decker is a 35-year-old ex-cop who left the force after witnessing a traumatic event that shook his faith in the system. Despite his newfound cynicism, he remains a driven individual with a strong moral code and a desire for justice. But now, operating outside the law, he must navigate the treacherous waters of the World of Darkness, using his streetwise cunning and unmatched determination to uncover the truth and protect the innocent.",
    stats: {
      physical: [
        { name: "Str", stat: 3 },
        { name: "Dex", stat: 2 },
        { name: "Sta", stat: 3 },
      ],
      mental: [
        { name: "Int", stat: 3 },
        { name: "Wis", stat: 2 },
        { name: "Wit", stat: 3 },
      ],
      social: [
        { name: "Pre", stat: 3 },
        { name: "Man", stat: 2 },
        { name: "Com", stat: 3 },
      ],
      skillPhy: [
        { name: "Athletics", stat: 3 },
        { name: "Brawl", stat: 2 },
        { name: "Drive", stat: 3 },
        { name: "Firearms", stat: 3 },
        { name: "Larceny", stat: 2 },
        { name: "Stealth", stat: 3 },
        { name: "Survival", stat: 3 },
        { name: "Weaponry", stat: 2 },
      ],
      skillMen: [
        { name: "Academics", stat: 3 },
        { name: "Computer", stat: 2 },
        { name: "Crafts", stat: 3 },
        { name: "Investigation", stat: 3 },
        { name: "Medicine", stat: 2 },
        { name: "Occult", stat: 3 },
        { name: "Politics", stat: 3 },
        { name: "Science", stat: 2 },
      ],
      skillSoc: [
        { name: "Animal Ken", stat: 3 },
        { name: "Empathy", stat: 2 },
        { name: "Expression", stat: 3 },
        { name: "Intimidation", stat: 3 },
        { name: "Persuasion", stat: 2 },
        { name: "Socialize", stat: 3 },
        { name: "Streetwise", stat: 3 },
        { name: "Subterfuge", stat: 2 },
      ],
    },
  },
  {
    id: "2",
    name: "Candy LeRoux",
    age: "21",
    location: "Colchester",
    profession: "Stripper",
    species: "Human",
    imageURL:
      "https://i.pinimg.com/originals/66/58/71/665871363fd206438c91e5d7e39c7b89.jpg",
    description:
      "Candy is a seasoned dancer in her late twenties, navigating the challenges of an industry that values youth and beauty above all else. Despite her tough exterior and streetwise savvy, she's starting to feel the effects of age and the fading of her looks. It was during one of her performances that she caught the eye of a mysterious patron, who seemed to possess a strange and unsettling allure. Though she's unsure what to make of him, she can't deny the thrill of danger that comes with his attention. As she finds herself drawn deeper into the World of Darkness, Candy must rely on her instincts and wits to survive in a world where the normal rules no longer apply.",
    stats: {
      physical: [
        { name: "Str", stat: 3 },
        { name: "Dex", stat: 2 },
        { name: "Sta", stat: 3 },
      ],
      mental: [
        { name: "Int", stat: 3 },
        { name: "Wis", stat: 2 },
        { name: "Wit", stat: 3 },
      ],
      social: [
        { name: "Pre", stat: 3 },
        { name: "Man", stat: 2 },
        { name: "Com", stat: 3 },
      ],
      skillPhy: [
        { name: "Athletics", stat: 3 },
        { name: "Brawl", stat: 2 },
        { name: "Drive", stat: 3 },
        { name: "Firearms", stat: 3 },
        { name: "Larceny", stat: 2 },
        { name: "Stealth", stat: 3 },
        { name: "Survival", stat: 3 },
        { name: "Weaponry", stat: 2 },
      ],
      skillMen: [
        { name: "Academics", stat: 3 },
        { name: "Computer", stat: 2 },
        { name: "Crafts", stat: 3 },
        { name: "Investigation", stat: 3 },
        { name: "Medicine", stat: 2 },
        { name: "Occult", stat: 3 },
        { name: "Politics", stat: 3 },
        { name: "Science", stat: 2 },
      ],
      skillSoc: [
        { name: "Animal Ken", stat: 3 },
        { name: "Empathy", stat: 2 },
        { name: "Expression", stat: 3 },
        { name: "Intimidation", stat: 3 },
        { name: "Persuasion", stat: 2 },
        { name: "Socialize", stat: 3 },
        { name: "Streetwise", stat: 3 },
        { name: "Subterfuge", stat: 2 },
      ],
    },
  },
  {
    id: "3",
    name: "Father David",
    age: "41",
    location: "Colchester",
    profession: "Charity Worker",
    species: "Human",
    imageURL:
      "https://images.fineartamerica.com/images-medium-large-5/the-mystery-of-faith-simeon-solomon.jpg",
    description:
      "Father David is a former Catholic priest who was forced to confront the harsh realities of the World of Darkness, causing a crisis of faith that led him to leave the Church. Despite his struggles with mental health issues and a battle with alcoholism, he remains driven to uncover the truth and protect those threatened by the forces of darkness. Operating as an independent exorcist, he uses his knowledge of the supernatural and unwavering determination to vanquish evil and bring peace to those in need. But as he delves deeper into the shadows, he must confront his own demons and the ghosts of his past, fighting to maintain his sanity and hold onto the hope that redemption may yet be possible.",
    stats: {
      physical: [
        { name: "Str", stat: 3 },
        { name: "Dex", stat: 2 },
        { name: "Sta", stat: 3 },
      ],
      mental: [
        { name: "Int", stat: 3 },
        { name: "Wis", stat: 2 },
        { name: "Wit", stat: 3 },
      ],
      social: [
        { name: "Pre", stat: 3 },
        { name: "Man", stat: 2 },
        { name: "Com", stat: 3 },
      ],
      skillPhy: [
        { name: "Athletics", stat: 3 },
        { name: "Brawl", stat: 2 },
        { name: "Drive", stat: 3 },
        { name: "Firearms", stat: 3 },
        { name: "Larceny", stat: 2 },
        { name: "Stealth", stat: 3 },
        { name: "Survival", stat: 3 },
        { name: "Weaponry", stat: 2 },
      ],
      skillMen: [
        { name: "Academics", stat: 3 },
        { name: "Computer", stat: 2 },
        { name: "Crafts", stat: 3 },
        { name: "Investigation", stat: 3 },
        { name: "Medicine", stat: 2 },
        { name: "Occult", stat: 3 },
        { name: "Politics", stat: 3 },
        { name: "Science", stat: 2 },
      ],
      skillSoc: [
        { name: "Animal Ken", stat: 3 },
        { name: "Empathy", stat: 2 },
        { name: "Expression", stat: 3 },
        { name: "Intimidation", stat: 3 },
        { name: "Persuasion", stat: 2 },
        { name: "Socialize", stat: 3 },
        { name: "Streetwise", stat: 3 },
        { name: "Subterfuge", stat: 2 },
      ],
    },
  },
];
